### ISSUE TITLE
Questions about the attack_name field

### ISSUE THREAD

**Issue by cgyzfjm** [shahriar0651/VehiGAN#4]
Hi, I have a few questions regarding the attack_name field that appears in the processed data:

1、Is the attack_name field generated based on the attack_type field in the original dataset?

2、Why does the attack_name field in the processed evaluation dataset not show "No Attack" for data where attack_type is "Genuine", but instead indicates a specific attack type? Could there be an issue with the logic used to generate the attack_name field?

Looking forward to your clarification. Thank you!

**Comment by cgyzfjm** [comment]
Is your intention that when the attack_type is "Genuine", the generated attack_name should be "No Attack", and when the attack_type corresponds to a specific attack, the attack_name should take the value of that specific attack_type?

The reason I’m asking is that while reading the run_ind_evaluation_pipeline.py script, I noticed that the generator requires data where attack_name is "No Attack". However, in the processed dataset at the evaluation stage, there seems to be no data with attack_name as "No Attack". This causes the following error:

```
Traceback (most recent call last):
  File "/mnt/c/Users/nzjds/Desktop/xxxxx/xxxxxx/VehiGAN-main/src/3_my_run_ind_evaluation_pipeline.py", line 186, in wgan_evaluate_pipeline
    gen_score = evaluate_generator(cfg, model_cfg, wgan, dataset_dict, gen_file_name)
  File "/mnt/c/Users/nzjds/Desktop/xxxxx/xxxxxxxx/VehiGAN-main/src/models/test_models/evaluate_generator.py", line 95, in evaluate_generator
  x_data = dataset_dict['No Attack']['x_data']

```
Looking forward to your clarification. Thank you again for your help!

**Comment by shahriar0651** [comment]
> Is your intention that when the attack_type is "Genuine", the generated attack_name should be "No Attack", and when the attack_type corresponds to a specific attack, the attack_name should take the value of that specific attack_type?

- Yes, `Genuine' indicates there is no attack.
 
*Troubleshooting the error*
---
Could you please confirm if your dataset is downloaded and placed correctly? Please follow these steps to get why the `dataset_dict` does not have 'No Attack' within it.

- Print  `dataset_dict.keys()` to ensure 'No Attack' is within it. You can do it by adding these as follows in (line 40/41) of `step_3_run_ind_detect_evaluation.py`:

```python
  dataset_dict = load_data_create_images(cfg) if not cfg.results_only else {}
  print("dataset_dict keys: ", dataset_dict.keys()) #add this line 
```
- Follow these previous steps (steps 1-2) and run 
  ```bash
  python step_3_run_ind_detect_evaluation.py -m models=wgan dataset=testing dataset.run_type=unit fast_load=True
  ```  
You should see something like the following:
```bash
Total attacks in the dataset:  (36,)
  0%|                                                                                                                                              | 0/5 [00:00<?, ?it/s]Attack Name:  No Attack
 20%|██████████████████████████▊                                                                                                           | 1/5 [00:00<00:03,  1.18it/s]Attack Name:  RandomPosition
 40%|█████████████████████████████████████████████████████▌                                                                                | 2/5 [00:01<00:02,  1.12it/s]Attack Name:  RandomPositionOffset
 60%|████████████████████████████████████████████████████████████████████████████████▍                                                     | 3/5 [00:02<00:01,  1.06it/s]Attack Name:  PlaygroundConstantPosition
 80%|███████████████████████████████████████████████████████████████████████████████████████████████████████████▏                          | 4/5 [00:03<00:00,  1.03it/s]Attack Name:  ConstantPositionOffset
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:04<00:00,  1.08it/s]
dataset_dict:  dict_keys(['No Attack', 'RandomPosition', 'RandomPositionOffset', 'PlaygroundConstantPosition', 'ConstantPositionOffset'])
```
Rather, if you see an empty dictionary or something else (without 'No Attack'), there seems to be an issue with the dataset loading. In that case, I would request you make sure you complete  `step 1` correctly (for both training and testing).

**Comment by cgyzfjm** [comment]
Here’s the English translation for your GitHub issue:

Grateful for your help!

I discovered that during the training phase, running `run_data_curation_pipeline.py` successfully generates "No Attack" data because only "Genuine" data is present. According to the following code snippet, "No Attack" data is generated:


```
attack_type_list = list(df_raw.attack_type.unique())
attack_type_list.remove("Genuine")
# -------------------------------------
if len(attack_type_list) == 0:
    attack_name = "No Attack"
elif len(attack_type_list) == 1:
    attack_name = attack_type_list[0]
else:
    attack_name = f"Multiple_{index}"

```

However, during the evaluation phase, if a dataset contains both "RandomSpeed" and "Genuine" data, the above code sets the `attack_name` of all rows in the dataset to "RandomSpeed." When I tried the following code snippet:
`df_raw["attack_type"].apply(lambda x: "No Attack" if x == "Genuine" else x)
`
to generate `attack_name` for each row based on its `attack_type` (i.e., rows with attack_type "RandomSpeed" have an attack_name of "RandomSpeed," while rows with attack_type "Genuine" have an `attack_name` of "No Attack"), I found that the AUROC was `NaN` and the AUPRC was 1.

![image](https://github.com/user-attachments/assets/cf292566-0b48-44bf-999d-1a65fce4a6e7)


After investigating, I discovered that this happens because the evaluation contains only one class of samples, causing these results. Based on my understanding, `attack_name` acts more like a dataset group ID, allowing normal and abnormal data related to a specific attack to be evaluated together, while the true determination of whether an attack is present is based on `attack_gt`. Consequently, I reverted to your original code, which then allowed the evaluation to proceed normally.

This is my current understanding. Please correct me if I am mistaken. I would greatly appreciate your guidance on the following questions:

1、I noticed that in the data processed by `run_data_curation_pipeline.py`, rows with `attack_type` as "Genuine" have an `attack_name` corresponding to a specific attack type rather than "No Attack." Does this mean that `attack_name` is more like a dataset group ID, grouping normal and abnormal data under a specific attack type for evaluation, while the actual determination of whether an attack occurred is based on `attack_gt`?

2、During the evaluation phase, since the dataset contains two types of data, it is not possible to generate "No Attack" data using the following snippet:

```
attack_type_list = list(df_raw.attack_type.unique())
attack_type_list.remove("Genuine")
if len(attack_type_list) == 0:
    attack_name = "No Attack"
elif len(attack_type_list) == 1:
    attack_name = attack_type_list[0]
else:
    attack_name = f"Multiple_{index}"

```
I modified the line in `evaluate_generator.py`:

```
x_data = dataset_dict['No Attack']['x_data']
```

to

```
x_data = np.concatenate([
    data['x_data'][np.where(data['y_data'] == 0)[0]]
    for data in dataset_dict.values()
], axis=0)

```
To avoid the issue of missing "No Attack" data when running:
`gen_score = evaluate_generator(cfg, model_cfg, wgan, dataset_dict, gen_file_name)`

through the above modification.

Is this modification valid?

3、In the future, I plan to collect data using the Carla simulation platform. For some fields in your dataset, I am unclear about their meanings. Could you please help clarify? Specifically:

- rv_id (Receiving vehicle ID),
- hv_id (Sending vehicle ID),
- target_id (?),
- rv_wsm_data (?),
- msg_generation_time (Timestamp when the sending vehicle sends the message),
- msg_rcv_time (Timestamp when the receiving vehicle receives the message),
- rv_msg_count (Total number of messages received by the receiving vehicle),
- rv_wsm_data (?),
- hv_wsm_data (?),
- hv_msg_count (Total number of messages sent by the sending vehicle),
- eebl_warn (?),
- ima_warn (?).

Thank you in advance for your assistance and guidance!

**Comment by shahriar0651** [comment]
> After investigating, I discovered that this happens because the evaluation contains only one class of samples, causing these results. Based on my understanding, attack_name acts more like a dataset group ID, allowing normal and abnormal data related to a specific attack to be evaluated together, while the true determination of whether an attack is present is based on attack_gt. Consequently, I reverted to your original code, which then allowed the evaluation to proceed normally.

> 1、I noticed that in the data processed by `run_data_curation_pipeline.py`, rows with `attack_type` as "Genuine" have an `attack_name` corresponding to a specific attack type rather than "No Attack." Does this mean that `attack_name` is more like a dataset group ID, grouping normal and abnormal data under a specific attack type for evaluation, while the actual determination of whether an attack occurred is based on `attack_gt`?

This is correct. Whereas `attack_name` indicates the dataset extension (what type of attack it contains), `attack_gt` indicates what exact row (BSM) contains such malicious content. 


> I modified the line in `evaluate_generator.py`:
> 
> ```
> x_data = dataset_dict['No Attack']['x_data']
> ```
> 
> to
> 
> ```
> x_data = np.concatenate([
>     data['x_data'][np.where(data['y_data'] == 0)[0]]
>     for data in dataset_dict.values()
> ], axis=0)
> 
> ```

No, you should not collect benign `x_data` in that way for the same reason as mentioned above.
`x_data = dataset_dict['No Attack']['x_data']` ensures that all the sequential BSMs are coming from a simulation where `No Attack` was present. You should retain the line `x_data = dataset_dict['No Attack']['x_data']`, and this should not be a problem if you follow the existing implementation. Please let me know if you still face the missing `No Attack` issue. 

> In the future, I plan to collect data using the Carla simulation platform. For some fields in your dataset, I am unclear about their meanings. Could you please help clarify?

The trace file generated after running a simulation is in the form of a Comma Separated Value (CSV) format. Each CSV contains the following columns:

|Column Header|Data Type|Description|
|-|-|-|
|`rv_id`|integer|identifier of the remote vehicle (transmitter of V2X message)|
|`hv_id`|integer|identifier of the host vehicle (receiver of V2X message)|
|`target_id`|integer|identifier of the target vehicle of the attack. This is especially useful for ghost-node based attacks to understand which vehicle is the target.|
|`msg_generation_time`|double|timestamp of when the message was generated at the transmitter|
|`msg_rcv_time`|double|timestamp of when the message was received at the receiver|
|`rv_msg_count`|integer|message sequence identifier or message count of the message transmitted by remote vehicle. This goes from 0 to 127 and resets to 0.|
|`rv_wsm_data`|string|additional data about the message|
|`rv_pos_x`|double|latitude of transmitter|
|`rv_pos_y`|double|longitude of transmitter|
|`rv_pos_z`|double|elevation of transmitter|
|`rv_speed`|double|speed of transmitter|
|`rv_accel`|double|acceleration of transmitter|
|`rv_heading`|double|heading/bearing/direction of transmitter|
|`rv_yaw_rate`|double|yaw-rate of transmitter|
|`rv_length`|double|length of transmitter vehicle|
|`rv_width`|double|width of transmitter vehicle|
|`rv_height`|double|height of transmitter vehicle|
|`hv_msg_count`|integer|message sequence identifier or message count of the message about to be transmitted by host vehicle. This goes from 0 to 127 and resets to 0.|
|`hv_wsm_data`|string|additional data about the message|
|`hv_pos_x`|double|latitude of receiver|
|`hv_pos_y`|double|longitude of receiver|
|`hv_pos_z`|double|elevation of receiver|
|`hv_speed`|double|speed of receiver|
|`hv_accel`|double|acceleration of receiver|
|`hv_heading`|double|heading/bearing/direction of receiver|
|`hv_length`|double|length of receiving vehicle|
|`hv_width`|double|width of receiving vehicle|
|`hv_height`|double|height of receiving vehicle|
|`attack_type`|string|type of attack if malicious/attacker vehicle, otherwise defaults to "Genuine"|
|`eebl_warn`|boolean|indicates if EEBL raised a warning; 1 = warning; 0 = no warning|
|`ima_warn`|boolean|indicates if IMA raised a warning; 1 = warning; 0 = no warning|

See more in [vasp's GitHub repo](https://github.com/quic/vasp/tree/0ec4af324f3ed729690f1cbd1b1143ebd7f4d6f4), particularly the [trace_file_column_explanation.md](https://github.com/quic/vasp/blob/0ec4af324f3ed729690f1cbd1b1143ebd7f4d6f4/docs/trace_file_column_explanation.md?plain=1#L36) in the [docs](https://github.com/quic/vasp/tree/0ec4af324f3ed729690f1cbd1b1143ebd7f4d6f4/docs)
folder.

**Comment by cgyzfjm** [comment]
I greatly appreciate your response - it has been immensely helpful.❤️

Regarding the absence of ['No Attack'] data in evaluate_generator.py, here's my understanding of **step_1_run_data_curation_pipeline.py**. Please correct me if I'm wrong:

During the training phase, when the dataset only contains Genuine data, after executing` attack_type_list.remove("Genuine")`, **attack_type_list==0**. Consequently, attack_name is set to "No Attack", and the dataset_dict contains No Attack data.

During the testing phase, when a dataset contains both **Genuine and specific attack data**, after executing `attack_type_list.remove("Genuine")`, only the "specific attack" data remains. This triggers the `elif len(attack_type_list) == 1: attack_name = attack_type_list[0] `code block, rather than the `if len(attack_type_list) == 0: attack_name = "No Attack"` condition. This explains why dataset_dict lacks No Attack data. (I'm wondering if there are any testing datasets in your provided data that contain only Genuine samples - if so, this error wouldn't occur.)

**Comment by shahriar0651** [comment]
```python
# Determine the name of the attack ----
# Extract the unique attack types from the `attack_type` column in the dataframe.
attack_type_list = list(df_raw.attack_type.unique())
```

Each simulation in VASP generates a separate `*.csv` file for its respective scenario, but the file names do not include the attack name. Each trace file includes Basic Safety Messages (BSMs) from both benign vehicles (`Genuine`) and potentially malicious vehicles. During simulation, both attackers and benign vehicles transmit BSMs, which are recorded in the files.  

To determine the attack type, all `*.csv` files from the dataset (training or testing) are loaded into the dataframe `df_raw`. The unique values in the `attack_type` column are extracted into `attack_type_list`.  
- If no attacks are simulated (`No Attack` scenario), the list contains only `"Genuine"`.  
- Otherwise, it contains both `"Genuine"` and the specific attack type (e.g., `"RandomSpeed"`).

```python
if len(attack_type_list) == 0:
    attack_name = "No Attack"
elif len(attack_type_list) == 1:
    attack_name = attack_type_list[0]
```

- If `attack_type_list` is empty, it indicates the absence of attack data, so `attack_name` is set to `"No Attack"`.  
- If the list contains only one entry (besides `"Genuine"`), it signifies a single attack type, and `attack_name` is set to this attack type, such as `RandomSpeed`.

**Additional Handling:**  
```python
else:
    attack_name = f"Multiple_{index}"
print(f"Attack name: {attack_name}")
```

- If multiple attack types remain after removing `"Genuine"`, the simulation involved varied attack BSMs. In such cases, the attack is labeled as `"Multiple_{index}"`, which we did not consider in our evaluation.

> This explains why dataset_dict lacks No Attack data. (I'm wondering if there are any testing datasets in your provided data that contain only Genuine samples - if so, this error wouldn't occur.)

Yes, the testing dataset folder contains (the first file) a file with only Genuine samples; hence, if you download the full dataset and run the data curation pipeline accurately, you should not face the missing `No Attack` case. Please let me know if you still face any issues running the scripts.

**Comment by cgyzfjm** [comment]
I'm truly grateful for your detailed and patient response. In my subsequent investigation, I discovered that my dataset was indeed missing the file that contains only Genuine samples. Once again, I extend my sincerest thanks.♥
